//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEPA.CCO.App.TransferMani.CepaWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aduana.gob.sv/", ConfigurationName="CepaWebService.WSManifiestoCEPA")]
    public interface WSManifiestoCEPA {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xmlData del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aduana.gob.sv/WSManifiestoCEPA/updateCepaDataRequest", ReplyAction="http://aduana.gob.sv/WSManifiestoCEPA/updateCepaDataResponse")]
        CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataResponse updateCepaData(CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xmlData del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aduana.gob.sv/WSManifiestoCEPA/getCepaDataRequest", ReplyAction="http://aduana.gob.sv/WSManifiestoCEPA/getCepaDataResponse")]
        CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataResponse getCepaData(CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xmlData del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aduana.gob.sv/WSManifiestoCEPA/getContenedorDataRequest", ReplyAction="http://aduana.gob.sv/WSManifiestoCEPA/getContenedorDataResponse")]
        CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataResponse getContenedorData(CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xmlData del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aduana.gob.sv/WSManifiestoCEPA/getDocumentoInfoDocumentoRequest", ReplyAction="http://aduana.gob.sv/WSManifiestoCEPA/getDocumentoInfoDocumentoResponse")]
        CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoResponse getDocumentoInfoDocumento(CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xmlData del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aduana.gob.sv/WSManifiestoCEPA/insertContenedorDANRequest", ReplyAction="http://aduana.gob.sv/WSManifiestoCEPA/insertContenedorDANResponse")]
        CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANResponse insertContenedorDAN(CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xmlData del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://aduana.gob.sv/WSManifiestoCEPA/validaContenedorDeclaRequest", ReplyAction="http://aduana.gob.sv/WSManifiestoCEPA/validaContenedorDeclaResponse")]
        CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaResponse validaContenedorDecla(CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateCepaDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateCepaData", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataRequestBody Body;
        
        public updateCepaDataRequest() {
        }
        
        public updateCepaDataRequest(CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class updateCepaDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        public updateCepaDataRequestBody() {
        }
        
        public updateCepaDataRequestBody(string xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateCepaDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateCepaDataResponse", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataResponseBody Body;
        
        public updateCepaDataResponse() {
        }
        
        public updateCepaDataResponse(CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class updateCepaDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public updateCepaDataResponseBody() {
        }
        
        public updateCepaDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCepaDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCepaData", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataRequestBody Body;
        
        public getCepaDataRequest() {
        }
        
        public getCepaDataRequest(CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCepaDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        public getCepaDataRequestBody() {
        }
        
        public getCepaDataRequestBody(string xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCepaDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCepaDataResponse", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataResponseBody Body;
        
        public getCepaDataResponse() {
        }
        
        public getCepaDataResponse(CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCepaDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCepaDataResponseBody() {
        }
        
        public getCepaDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getContenedorDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getContenedorData", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataRequestBody Body;
        
        public getContenedorDataRequest() {
        }
        
        public getContenedorDataRequest(CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getContenedorDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        public getContenedorDataRequestBody() {
        }
        
        public getContenedorDataRequestBody(string xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getContenedorDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getContenedorDataResponse", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataResponseBody Body;
        
        public getContenedorDataResponse() {
        }
        
        public getContenedorDataResponse(CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getContenedorDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getContenedorDataResponseBody() {
        }
        
        public getContenedorDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentoInfoDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentoInfoDocumento", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoRequestBody Body;
        
        public getDocumentoInfoDocumentoRequest() {
        }
        
        public getDocumentoInfoDocumentoRequest(CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDocumentoInfoDocumentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        public getDocumentoInfoDocumentoRequestBody() {
        }
        
        public getDocumentoInfoDocumentoRequestBody(string xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentoInfoDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentoInfoDocumentoResponse", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoResponseBody Body;
        
        public getDocumentoInfoDocumentoResponse() {
        }
        
        public getDocumentoInfoDocumentoResponse(CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDocumentoInfoDocumentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDocumentoInfoDocumentoResponseBody() {
        }
        
        public getDocumentoInfoDocumentoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertContenedorDANRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertContenedorDAN", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANRequestBody Body;
        
        public insertContenedorDANRequest() {
        }
        
        public insertContenedorDANRequest(CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertContenedorDANRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        public insertContenedorDANRequestBody() {
        }
        
        public insertContenedorDANRequestBody(string xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertContenedorDANResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertContenedorDANResponse", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANResponseBody Body;
        
        public insertContenedorDANResponse() {
        }
        
        public insertContenedorDANResponse(CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertContenedorDANResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public insertContenedorDANResponseBody() {
        }
        
        public insertContenedorDANResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaContenedorDeclaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaContenedorDecla", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaRequestBody Body;
        
        public validaContenedorDeclaRequest() {
        }
        
        public validaContenedorDeclaRequest(CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validaContenedorDeclaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        public validaContenedorDeclaRequestBody() {
        }
        
        public validaContenedorDeclaRequestBody(string xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaContenedorDeclaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaContenedorDeclaResponse", Namespace="http://aduana.gob.sv/", Order=0)]
        public CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaResponseBody Body;
        
        public validaContenedorDeclaResponse() {
        }
        
        public validaContenedorDeclaResponse(CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validaContenedorDeclaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public validaContenedorDeclaResponseBody() {
        }
        
        public validaContenedorDeclaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSManifiestoCEPAChannel : CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSManifiestoCEPAClient : System.ServiceModel.ClientBase<CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA>, CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA {
        
        public WSManifiestoCEPAClient() {
        }
        
        public WSManifiestoCEPAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSManifiestoCEPAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSManifiestoCEPAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSManifiestoCEPAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataResponse CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA.updateCepaData(CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataRequest request) {
            return base.Channel.updateCepaData(request);
        }
        
        public string updateCepaData(string xmlData) {
            CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataRequest inValue = new CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataRequest();
            inValue.Body = new CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataRequestBody();
            inValue.Body.xmlData = xmlData;
            CEPA.CCO.App.TransferMani.CepaWebService.updateCepaDataResponse retVal = ((CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA)(this)).updateCepaData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataResponse CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA.getCepaData(CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataRequest request) {
            return base.Channel.getCepaData(request);
        }
        
        public string getCepaData(string xmlData) {
            CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataRequest inValue = new CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataRequest();
            inValue.Body = new CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataRequestBody();
            inValue.Body.xmlData = xmlData;
            CEPA.CCO.App.TransferMani.CepaWebService.getCepaDataResponse retVal = ((CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA)(this)).getCepaData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataResponse CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA.getContenedorData(CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataRequest request) {
            return base.Channel.getContenedorData(request);
        }
        
        public string getContenedorData(string xmlData) {
            CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataRequest inValue = new CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataRequest();
            inValue.Body = new CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataRequestBody();
            inValue.Body.xmlData = xmlData;
            CEPA.CCO.App.TransferMani.CepaWebService.getContenedorDataResponse retVal = ((CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA)(this)).getContenedorData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoResponse CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA.getDocumentoInfoDocumento(CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoRequest request) {
            return base.Channel.getDocumentoInfoDocumento(request);
        }
        
        public string getDocumentoInfoDocumento(string xmlData) {
            CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoRequest inValue = new CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoRequest();
            inValue.Body = new CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoRequestBody();
            inValue.Body.xmlData = xmlData;
            CEPA.CCO.App.TransferMani.CepaWebService.getDocumentoInfoDocumentoResponse retVal = ((CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA)(this)).getDocumentoInfoDocumento(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANResponse CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA.insertContenedorDAN(CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANRequest request) {
            return base.Channel.insertContenedorDAN(request);
        }
        
        public string insertContenedorDAN(string xmlData) {
            CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANRequest inValue = new CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANRequest();
            inValue.Body = new CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANRequestBody();
            inValue.Body.xmlData = xmlData;
            CEPA.CCO.App.TransferMani.CepaWebService.insertContenedorDANResponse retVal = ((CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA)(this)).insertContenedorDAN(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaResponse CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA.validaContenedorDecla(CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaRequest request) {
            return base.Channel.validaContenedorDecla(request);
        }
        
        public string validaContenedorDecla(string xmlData) {
            CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaRequest inValue = new CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaRequest();
            inValue.Body = new CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaRequestBody();
            inValue.Body.xmlData = xmlData;
            CEPA.CCO.App.TransferMani.CepaWebService.validaContenedorDeclaResponse retVal = ((CEPA.CCO.App.TransferMani.CepaWebService.WSManifiestoCEPA)(this)).validaContenedorDecla(inValue);
            return retVal.Body.@return;
        }
    }
}
